### ISSUE TITLE
How do I get logged in user email id?

### ISSUE THREAD

**Issue by himangipatel** [actions-on-google/dialogflow-helper-intents-nodejs#9] opened 2019-08-05 09:14 UTC
I have an access token of user which I got as below,
` const accessToken = req.body.originalDetectIntentRequest.payload.user.accessToken;`

how can I get logged in user emailid,name and user's other details?

**Comment by Fleker** [comment] 2019-08-05 14:00
Duplicate of https://github.com/actions-on-google/actions-on-google-nodejs/issues/347

**Closed as completed by Fleker** 2019-08-05 14:00 UTC
